use customer_shopping_behaviour;  #already created database as customer_shopping_behaviour

select * from customer limit 20;

#Q1. What is the total revenue generated by male vs. female customers?
select Gender, sum(`Purchase_Amount($)`) as Total_Revenue
from customer 
group by Gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    Customer_ID,
    Gender,
    Item_Purchased,
    `Purchase_Amount($)`
FROM customer
WHERE Discount_Applied = 'Yes'
AND `Purchase_Amount($)` >
(
    SELECT AVG(`Purchase_Amount($)`)
    FROM customer
);

#Q3. Which are the top 5 products with the highest average review rating?
SELECT
    Item_Purchased,
    AVG(Review_Rating) AS Avg_Rating
FROM customer
GROUP BY Item_Purchased
ORDER BY Avg_Rating DESC
LIMIT 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
    Shipping_Type,
    AVG(`Purchase_Amount($)`) AS Avg_Purchase
FROM customer
WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    Subscription_Status,
    AVG(`Purchase_Amount($)`) AS Avg_Spend,
    SUM(`Purchase_Amount($)`) AS Total_Revenue,
    COUNT(*) AS Total_Customers
FROM customer
GROUP BY Subscription_Status;

#Q6. which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    Item_Purchased,
    ROUND(
        100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS Discount_Percentage
FROM customer
GROUP BY Item_Purchased
ORDER BY Discount_Percentage DESC
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count
FROM
(
    SELECT
        Customer_ID,
        CASE
            WHEN Previous_Purchases <= 5 THEN 'New'
            WHEN Previous_Purchases <= 15 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customer
) AS Segments
GROUP BY Customer_Segment;

#Q8. What are the top 3 most purchased products within each category?
WITH ProductCounts AS
(
    SELECT
        Category,
        Item_Purchased,
        COUNT(*) AS Purchase_Count,
        ROW_NUMBER() OVER
        (
            PARTITION BY Category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY Category, Item_Purchased
)
SELECT
    Category,
    Item_Purchased,
    Purchase_Count
FROM ProductCounts
WHERE rn <= 3;

#09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    Subscription_Status,
    COUNT(*) AS Customer_Count
FROM customer
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;

#Q10. What is the revenue contribution of each age group?
SELECT
    Age_Group,
    SUM(`Purchase_Amount($)`) AS Total_Revenue
FROM customer
GROUP BY Age_Group
ORDER BY Total_Revenue DESC;